#!/bin/bash
if [[ ($# -ne 1 && $# -ne 2) ]]; then
  echo "Usage: fvi [path] <filename patther>"
fi

if [ "$#" -eq 1 ]; then
  find . -name "$1" -exec vi {} \;
else
   find "$1" -name "$2" -exec vi {} \;
fi
